"""create shipments

Revision ID: 09488665357e
Revises: b7ce8389f6a2
Create Date: 2026-09-23 12:06:39.868430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09488665357e'
down_revision: Union[str, Sequence[str], None] = 'b7ce8389f6a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('shipment_no', sa.String(length=32), sa.Computed("'SHP-' || lpad(id::text, greatest(6, length(id::text)), '0')", ), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('sender_address', sa.String(length=500), nullable=False),
    sa.Column('recipient_address', sa.String(length=500), nullable=False),
    sa.Column('region_code', sa.String(length=1), server_default='Z', nullable=False),
    sa.Column('stage', sa.String(length=32), server_default='PENDING_PICKUP', nullable=False),
    sa.Column('last_scanned_station_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(stage IN ('PENDING_PICKUP', 'PICKED_UP') AND last_scanned_station_id IS NULL) OR (stage NOT IN ('PENDING_PICKUP', 'PICKED_UP') AND last_scanned_station_id IS NOT NULL)", name='ck_shipments_scanned_station'),
    sa.CheckConstraint("region_code = 'Z'", name='ck_shipments_region'),
    sa.CheckConstraint("stage IN ('PENDING_PICKUP', 'PICKED_UP', 'AT_A', 'IN_TRANSIT_AB', 'AT_B', 'IN_TRANSIT_BC', 'AT_C', 'OUT_FOR_DELIVERY', 'SIGNED')", name='ck_shipments_stage'),
    sa.CheckConstraint('length(btrim(sender_address)) > 0 AND length(btrim(recipient_address)) > 0', name='ck_shipments_addresses'),
    sa.ForeignKeyConstraint(['last_scanned_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('shipment_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    # ### end Alembic commands ###
