"""create orders

Revision ID: 2b703bcfbb9f
Revises: 4c5a234a0a46
Create Date: 2026-09-22 14:00:32.214897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b703bcfbb9f'
down_revision: Union[str, Sequence[str], None] = '4c5a234a0a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('order_no', sa.String(length=32), sa.Computed("'ORD-' || lpad(id::text, greatest(6, length(id::text)), '0')", ), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=False),
    sa.Column('sender_address', sa.String(length=500), nullable=False),
    sa.Column('recipient_name', sa.String(length=100), nullable=False),
    sa.Column('recipient_address', sa.String(length=500), nullable=False),
    sa.Column('region_code', sa.String(length=1), server_default='Z', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PENDING_SHIPMENT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("region_code = 'Z'", name='ck_orders_region'),
    sa.CheckConstraint("status IN ('PENDING_SHIPMENT', 'SHIPMENT_CREATED', 'COMPLETED')", name='ck_orders_status'),
    sa.CheckConstraint('length(btrim(product_name)) > 0 AND length(btrim(sender_name)) > 0 AND length(btrim(sender_address)) > 0 AND length(btrim(recipient_name)) > 0 AND length(btrim(recipient_address)) > 0', name='ck_orders_nonblank'),
    sa.CheckConstraint('quantity > 0', name='ck_orders_quantity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
