"""structured sender recipient addresses

Revision ID: 30ec3dbeb8ac
Revises: 77292ad0db58
Create Date: 2026-10-01 23:27:31.622778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ec3dbeb8ac'
down_revision: Union[str, Sequence[str], None] = '77292ad0db58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('sender_province_id', sa.BigInteger(), nullable=True))
    op.add_column('orders', sa.Column('sender_province_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('sender_city_id', sa.BigInteger(), nullable=True))
    op.add_column('orders', sa.Column('sender_city_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('sender_district_id', sa.BigInteger(), nullable=True))
    op.add_column('orders', sa.Column('sender_district_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('recipient_province_id', sa.BigInteger(), nullable=True))
    op.add_column('orders', sa.Column('recipient_province_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('recipient_city_id', sa.BigInteger(), nullable=True))
    op.add_column('orders', sa.Column('recipient_city_name', sa.String(length=100), nullable=True))
    op.add_column('orders', sa.Column('recipient_district_id', sa.BigInteger(), nullable=True))
    op.add_column('orders', sa.Column('recipient_district_name', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'orders', 'districts', ['recipient_district_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'orders', 'provinces', ['sender_province_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'orders', 'cities', ['sender_city_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'orders', 'provinces', ['recipient_province_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'orders', 'cities', ['recipient_city_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'orders', 'districts', ['sender_district_id'], ['id'], ondelete='RESTRICT')
    op.add_column('shipments', sa.Column('sender_province_id', sa.BigInteger(), nullable=True))
    op.add_column('shipments', sa.Column('sender_province_name', sa.String(length=100), nullable=True))
    op.add_column('shipments', sa.Column('sender_city_id', sa.BigInteger(), nullable=True))
    op.add_column('shipments', sa.Column('sender_city_name', sa.String(length=100), nullable=True))
    op.add_column('shipments', sa.Column('sender_district_id', sa.BigInteger(), nullable=True))
    op.add_column('shipments', sa.Column('sender_district_name', sa.String(length=100), nullable=True))
    op.add_column('shipments', sa.Column('recipient_province_id', sa.BigInteger(), nullable=True))
    op.add_column('shipments', sa.Column('recipient_province_name', sa.String(length=100), nullable=True))
    op.add_column('shipments', sa.Column('recipient_city_id', sa.BigInteger(), nullable=True))
    op.add_column('shipments', sa.Column('recipient_city_name', sa.String(length=100), nullable=True))
    op.add_column('shipments', sa.Column('recipient_district_id', sa.BigInteger(), nullable=True))
    op.add_column('shipments', sa.Column('recipient_district_name', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'shipments', 'cities', ['sender_city_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'shipments', 'cities', ['recipient_city_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'shipments', 'provinces', ['recipient_province_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'shipments', 'districts', ['sender_district_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'shipments', 'provinces', ['sender_province_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'shipments', 'districts', ['recipient_district_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    raise RuntimeError('restore the pre-upgrade backup; structured address snapshots must not be discarded.')
