"""create operation logs

Revision ID: 4c5a234a0a46
Revises: 5653bf12321f
Create Date: 2026-09-21 17:05:55.568898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c5a234a0a46'
down_revision: Union[str, Sequence[str], None] = '5653bf12321f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_status', sa.SmallInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("request_hash ~ '^[0-9a-f]{64}$'", name='ck_logs_hash'),
    sa.CheckConstraint("resource_type IN ('ORDER', 'SHIPMENT', 'TRANSPORT_TASK', 'CLOCK')", name='ck_logs_resource_type'),
    sa.CheckConstraint('response_status IN (200, 201)', name='ck_logs_response_status'),
    sa.CheckConstraint(
        'length(btrim(action)) > 0',
        name='ck_logs_action',
    ),
    sa.CheckConstraint(
        'resource_id > 0',
        name='ck_logs_resource_id',
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_logs')
    # ### end Alembic commands ###
