"""create simulation settings

Revision ID: 5653bf12321f
Revises: 
Create Date: 2026-09-21 16:21:41.999543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5653bf12321f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_settings',
    sa.Column(
        'id',
        sa.BigInteger(),
        autoincrement=False,
        nullable=False,
    ),
    sa.Column('current_time', sa.DateTime(timezone=True), server_default=sa.text("TIMESTAMPTZ '2026-09-20 08:00:00+08:00'"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('"current_time" >= TIMESTAMPTZ \'2026-09-20 08:00:00+08:00\'', name='ck_simulation_start'),
    sa.CheckConstraint('id = 1', name='ck_simulation_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_settings')
    # ### end Alembic commands ###
