"""domestic province city district dictionary

Revision ID: 77292ad0db58
Revises: f72d8a94c105
Create Date: 2026-10-01 23:22:38.427186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77292ad0db58'
down_revision: Union[str, Sequence[str], None] = 'f72d8a94c105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
    sa.Column('kind', sa.String(length=32), server_default='PROVINCE', nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[0-9]{2,12}$'", name='ck_provinces_code'),
    sa.CheckConstraint("kind IN ('PROVINCE','AUTONOMOUS_REGION','MUNICIPALITY','SPECIAL_ADMINISTRATIVE_REGION')", name='ck_provinces_kind'),
    sa.CheckConstraint('length(btrim(name)) > 0', name='ck_provinces_name'),
    sa.CheckConstraint('sort_order >= 0', name='ck_provinces_sort'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cities',
    sa.Column('province_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[0-9]{2,12}$'", name='ck_cities_code'),
    sa.CheckConstraint('length(btrim(name)) > 0', name='ck_cities_name'),
    sa.CheckConstraint('sort_order >= 0', name='ck_cities_sort'),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('id', 'province_id', name='uq_cities_id_province')
    )
    op.create_index('ix_cities_province', 'cities', ['province_id'], unique=False)
    op.create_table('districts',
    sa.Column('province_id', sa.BigInteger(), nullable=False),
    sa.Column('city_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("code ~ '^[0-9]{2,12}$'", name='ck_districts_code'),
    sa.CheckConstraint('length(btrim(name)) > 0', name='ck_districts_name'),
    sa.CheckConstraint('sort_order >= 0', name='ck_districts_sort'),
    sa.ForeignKeyConstraint(['city_id', 'province_id'], ['cities.id', 'cities.province_id'], name='fk_districts_city_province', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_districts_parent', 'districts', ['province_id', 'city_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    connection = op.get_bind()
    for table in ('districts', 'cities', 'provinces'):
        if connection.execute(sa.text(f'SELECT EXISTS (SELECT 1 FROM {table})')).scalar():
            raise RuntimeError('Address dictionary contains data; restore the pre-upgrade backup instead.')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_districts_parent', table_name='districts')
    op.drop_table('districts')
    op.drop_index('ix_cities_province', table_name='cities')
    op.drop_table('cities')
    op.drop_table('provinces')
    # ### end Alembic commands ###
