"""create tasks and tracking events

Revision ID: a6b205da2353
Revises: 09488665357e
Create Date: 2026-09-23 12:34:02.807551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b205da2353'
down_revision: Union[str, Sequence[str], None] = '09488665357e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_tasks',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('task_no', sa.String(length=32), sa.Computed("'TRIP-' || lpad(id::text, greatest(6, length(id::text)), '0')", ), nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='PENDING_DEPARTURE', nullable=False),
    sa.Column('expected_arrival_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'PENDING_DEPARTURE' AND departed_at IS NULL AND arrived_at IS NULL) OR (status = 'IN_TRANSIT' AND departed_at IS NOT NULL AND arrived_at IS NULL) OR (status = 'ARRIVED' AND departed_at IS NOT NULL AND arrived_at IS NOT NULL AND arrived_at >= departed_at)", name='ck_tasks_status_times'),
    sa.ForeignKeyConstraint(['route_id'], ['transport_routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_no')
    )
    op.create_table('tracking_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('station_id', sa.BigInteger(), nullable=True),
    sa.Column('task_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(event_type IN ('DEPART_AB', 'ARRIVE_B', 'DEPART_BC', 'ARRIVE_C') AND task_id IS NOT NULL) OR (event_type NOT IN ('DEPART_AB', 'ARRIVE_B', 'DEPART_BC', 'ARRIVE_C') AND task_id IS NULL)", name='ck_events_task'),
    sa.CheckConstraint("(event_type IN ('ENTER_A', 'DEPART_AB', 'ARRIVE_B', 'DEPART_BC', 'ARRIVE_C') AND station_id IS NOT NULL) OR (event_type IN ('SHIPMENT_CREATED', 'PICKUP', 'START_DELIVERY', 'SIGN') AND station_id IS NULL)", name='ck_events_station'),
    sa.CheckConstraint("event_type IN ('SHIPMENT_CREATED', 'PICKUP', 'ENTER_A', 'DEPART_AB', 'ARRIVE_B', 'DEPART_BC', 'ARRIVE_C', 'START_DELIVERY', 'SIGN')", name='ck_events_type'),
    sa.ForeignKeyConstraint(['operation_id'], ['operation_logs.id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['transport_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id', 'shipment_id', 'event_type', name='uq_events_operation')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracking_events')
    op.drop_table('transport_tasks')
    # ### end Alembic commands ###
