"""create network tables

Revision ID: b7ce8389f6a2
Revises: 2b703bcfbb9f
Create Date: 2026-09-22 18:00:50.120588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ce8389f6a2'
down_revision: Union[str, Sequence[str], None] = '2b703bcfbb9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=1), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.CheckConstraint("code IN ('A', 'B', 'C')", name='ck_stations_code'),
    sa.CheckConstraint('length(btrim(name)) > 0', name='ck_stations_name'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('transport_routes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('origin_station_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_station_id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("code IN ('AB', 'BC')", name='ck_routes_code'),
    sa.CheckConstraint('origin_station_id <> destination_station_id', name='ck_routes_distinct_stations'),
    sa.ForeignKeyConstraint(['destination_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['origin_station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('origin_station_id', 'destination_station_id', name='uq_routes_endpoints')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transport_routes')
    op.drop_table('stations')
    # ### end Alembic commands ###
