"""create task shipments

Revision ID: ccce65c68961
Revises: a6b205da2353
Create Date: 2026-09-23 22:53:48.182430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccce65c68961'
down_revision: Union[str, Sequence[str], None] = 'a6b205da2353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_shipments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['transport_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'shipment_id', name='uq_task_shipments')
    )
    op.create_index('ix_task_shipments_shipment', 'task_shipments', ['shipment_id', 'task_id'], unique=False)
    op.create_index('uq_task_shipments_active', 'task_shipments', ['shipment_id'], unique=True, postgresql_where=sa.text('released_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_task_shipments_active', table_name='task_shipments', postgresql_where=sa.text('released_at IS NULL'))
    op.drop_index('ix_task_shipments_shipment', table_name='task_shipments')
    op.drop_table('task_shipments')
    # ### end Alembic commands ###
