"""reviewed shipment schedules and future task reservations

Revision ID: f72d8a94c105
Revises: e61a7c93b204
Create Date: 2026-10-01 16:46:51.851509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f72d8a94c105'
down_revision: Union[str, Sequence[str], None] = 'e61a7c93b204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_schedule_versions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('shipment_id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('path_version', sa.Integer(), nullable=False),
    sa.Column('origin_station_id', sa.BigInteger(), nullable=False),
    sa.Column('destination_station_id', sa.BigInteger(), nullable=False),
    sa.Column('source_plan_id', sa.BigInteger(), nullable=True),
    sa.Column('source_plan_version', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('legs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('operation_id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("jsonb_typeof(legs) = 'array'", name='ck_shipment_schedule_legs'),
    sa.CheckConstraint('version > 0', name='ck_shipment_schedule_version'),
    sa.ForeignKeyConstraint(['destination_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operation_logs.id'], ),
    sa.ForeignKeyConstraint(['origin_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['source_plan_id'], ['path_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id', 'version', name='uq_shipment_schedule_versions')
    )
    op.add_column('operation_logs', sa.Column('parent_operation_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'operation_logs', 'operation_logs', ['parent_operation_id'], ['id'])
    op.add_column('path_plan_legs', sa.Column('origin_transfer_override_minutes', sa.Integer(), nullable=True))
    op.add_column('shipment_path_legs', sa.Column('travel_reference_minutes', sa.Integer(), nullable=True))
    op.add_column('shipment_path_legs', sa.Column('origin_transfer_reference_minutes', sa.Integer(), nullable=True))
    op.add_column('shipments', sa.Column('scheduling_mode', sa.String(length=16), server_default='LEGACY', nullable=False))
    op.add_column('shipments', sa.Column('schedule_version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('shipments', sa.Column('schedule_status', sa.String(length=32), server_default='NOT_CONFIRMED', nullable=False))
    op.add_column('shipments', sa.Column('schedule_reason', sa.String(length=500), nullable=True))
    op.add_column('stations', sa.Column('transfer_minutes', sa.Integer(), nullable=True))
    op.add_column('task_shipments', sa.Column('association_state', sa.String(length=16), server_default='ACTIVE', nullable=False))
    op.add_column('task_shipments', sa.Column('schedule_version', sa.Integer(), nullable=True))
    op.add_column('task_shipments', sa.Column('predecessor_association_id', sa.BigInteger(), nullable=True))
    op.add_column('task_shipments', sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_shipments', sa.Column('approved_transfer_minutes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('task_shipments', sa.Column('planned_origin_arrival_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_shipments', sa.Column('release_reason', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'task_shipments', 'task_shipments', ['predecessor_association_id'], ['id'])
    op.add_column('transport_routes', sa.Column('travel_minutes', sa.Integer(), nullable=True))
    op.add_column('transport_tasks', sa.Column('scheduling_source', sa.String(length=16), server_default='LEGACY', nullable=False))
    op.add_column('transport_tasks', sa.Column('planned_departure_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transport_tasks', sa.Column('planned_travel_minutes', sa.Integer(), nullable=True))
    op.add_column('transport_tasks', sa.Column('schedule_revision', sa.Integer(), server_default='1', nullable=False))
    op.execute("UPDATE task_shipments SET association_state = 'RELEASED' WHERE released_at IS NOT NULL")
    op.drop_index('uq_task_shipments_active', table_name='task_shipments')
    op.drop_index('uq_task_shipments_active_leg', table_name='task_shipments')
    op.create_index('uq_task_shipments_active', 'task_shipments', ['shipment_id'], unique=True,
                    postgresql_where=sa.text("association_state = 'ACTIVE'"))
    op.create_index('uq_task_shipments_active_leg', 'task_shipments', ['path_leg_id'], unique=True,
                    postgresql_where=sa.text("association_state IN ('PLANNED','ACTIVE') AND path_leg_id IS NOT NULL"))
    op.drop_constraint('ck_tasks_status_times', 'transport_tasks', type_='check')
    op.create_check_constraint('ck_tasks_status_times', 'transport_tasks',
        "((status IN ('PENDING_DEPARTURE','WAITING_CARGO','WAITING_PREDECESSOR') AND departed_at IS NULL AND arrived_at IS NULL) "
        "OR (status = 'IN_TRANSIT' AND departed_at IS NOT NULL AND arrived_at IS NULL) "
        "OR (status = 'ARRIVED' AND departed_at IS NOT NULL AND arrived_at IS NOT NULL AND arrived_at >= departed_at)) "
        "AND cancelled_at IS NULL AND cancel_reason IS NULL OR (status = 'CANCELLED' AND departed_at IS NULL "
        "AND arrived_at IS NULL AND cancelled_at IS NOT NULL AND cancel_reason IS NOT NULL "
        "AND length(btrim(cancel_reason)) BETWEEN 1 AND 500)")
    checks = {
        'stations': [('ck_stations_transfer', 'transfer_minutes BETWEEN 0 AND 525600')],
        'transport_routes': [('ck_routes_travel', 'travel_minutes BETWEEN 1 AND 525600')],
        'path_plan_legs': [('ck_path_plan_legs_transfer', 'origin_transfer_override_minutes BETWEEN 0 AND 525600')],
        'shipments': [('ck_shipments_schedule_version', 'schedule_version >= 0'),
            ('ck_shipments_schedule_mode', "scheduling_mode IN ('LEGACY','REVIEWED')"),
            ('ck_shipments_schedule_status', "schedule_status IN ('NOT_CONFIRMED','CONFIRMED','NEEDS_RECONFIRMATION','BLOCKED','COMPLETED')")],
        'task_shipments': [('ck_task_shipments_state', "(association_state IN ('PLANNED','ACTIVE') AND released_at IS NULL) OR (association_state = 'RELEASED' AND released_at IS NOT NULL)"),
            ('ck_task_shipments_transfer', 'approved_transfer_minutes BETWEEN 0 AND 525600')],
        'transport_tasks': [('ck_tasks_schedule_revision', 'schedule_revision > 0'),
            ('ck_tasks_schedule_source', "scheduling_source IN ('LEGACY','PLAN')"),
            ('ck_tasks_travel', 'planned_travel_minutes BETWEEN 1 AND 525600'),
            ('ck_tasks_plan_times', "scheduling_source = 'LEGACY' OR (planned_departure_at IS NOT NULL AND planned_travel_minutes IS NOT NULL AND expected_arrival_at > planned_departure_at)")],
    }
    for table, entries in checks.items():
        for name, expression in entries:
            op.create_check_constraint(name, table, expression)



def downgrade() -> None:
    raise RuntimeError("restore the pre-upgrade backup; V7 future task chains cannot be downgraded safely.")
